(refactoring) changed display according to design
splendid-pdf/yandex-market pull request #105
Opened 2023-03-20 13:15 UTC by DameerGamlet

С соображения оптимизации передаём только те данные, которые требуют:
Новый результат выполнения:
```
Hibernate: 
    select
        p2_0.url,
        p1_0.external_id,
        p1_0.seller_external_id,
        p1_0.name,
        p1_0.article_number,
        p1_0.price,
        p1_0.count,
        p1_0.is_visible,
        t1_0.name,
        p1_0.creation_date,
        p1_0.is_deleted 
    from
        products p1_0 
    join
        product_images p2_0 
            on p2_0.product_id=p1_0.id 
            and p2_0.is_main=true 
    join
        types t1_0 
            on p1_0.type_id=t1_0.id 
    where
        p1_0.seller_external_id=? 
        and p1_0.is_deleted=case 
            when ?='PRODUCT_LIST' then true 
            when ?='ARCHIVE' then false 
            else false 
        end 
```
Модель "Превью" на основе следующего дизайна:
![image](https://user-images.githubusercontent.com/74682814/226349617-38779091-62b9-40b2-9122-5c03ed1a4bd4.png)

Фактический результат:
![image](https://user-images.githubusercontent.com/74682814/226350566-d046c502-eeaf-4851-825d-43c8310e061f.png)

2023-03-20 13:19 UTC, DameerGamlet commented
Также анализ запрос:
![image](https://user-images.githubusercontent.com/74682814/226350949-e8b5a8ac-6674-4714-806f-c74c4482a958.png)

2023-03-20 15:47 UTC, askfarz approved these changes

2023-03-20 15:47 UTC, AskarovFarkhad commented on product-service/src/main/java/com/yandex/market/productservice/dto/projections/ProductSellerPreview.java
> +public interface ProductSellerPreview {
Поле количество не забыл?

2023-03-20 16:50 UTC, seniorio-batonio commented on product-service/src/main/java/com/yandex/market/productservice/dto/projections/ProductSellerPreview.java
> +public interface ProductSellerPreview {
Превью продукта селлера? Превью продуктового селлера? запутался

2023-03-20 16:55 UTC, seniorio-batonio requested changes
1. Запросец тяжелый - это показывает эксплейн аналайз.
а вот вычисление для is_deleted через кейс это уже перебор)
продумайте с командой получше как это хранить.
2. время возвращается разложенным в массиве, но изначально договаривались следовать ISO 8601

2023-03-20 22:07 UTC, seniorio-batonio approved these changes

2023-03-21 09:28 UTC, merged

2023-03-21 10:29 UTC, DameerGamlet commented
@seniorio-batonio  В новом ПР будет залито изменение формата с:
```
"creationDate": [
                2023,
                3,
                21
            ],
```
на 
```
            "creationDate": "2023-03-21",
```