Feature/add mod tests for product
splendid-pdf/yandex-market pull request #154
Opened 2023-04-22 20:48 UTC by DameerGamlet

Тесты на эндпоинты

2023-04-23 12:00 UTC, eseoa requested changes

2023-04-23 12:00 UTC, eseoa commented on product-service/src/test/java/com/yandex/market/productservice/ProductControllerModuleTest.java
> +class ProductControllerModuleTest {
по моему этот класс не будет работать правильно. Когда мы работаем с тест контейнерами их надо проинициализировать. В идеале создать абстрактный класс например `IntegrationTest `на него повесить аннотации 
```
@SpringBootTest
@Testcontainers
@ActiveProfiles("testcontainers")
@TestPropertySource(locations = "classpath:application-test.yaml")
```
Затем в нем настроить запуск необходимых контейнеров. Вот пример:

```
// если не указать версия по умолчания latest 
private static final MongoDBContainer mongoDBContainer =
            new MongoDBContainer(DockerImageName.parse("тег имеджа: версия"));

// запускаем контейнер, не парься что классов будет много наследоваться от этого абстрактного класса. Контейнер айди присваивается только при первом запуске и если он присвоен то у тебя новый контейнер не запустится 
    @BeforeAll
    static void runContainer() {
        mongoDBContainer.start();
    }

// надо динамически определять урл во время выполнения тестов.
    @DynamicPropertySource
    static void mongoProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.data.mongo.url", mongoDBContainer::getReplicaSetUrl);
    }
```
Это пример с монгой, но с постгресом не сильно что - то поменяется. Также не забудь про юзернейм и пароль
Чтобы убедиться в работоспособности зайди в свои докер контейнеры и посмотри что у тебя поднялось два контейнера. Один с тестовой бд, а второй нужен чтобы отслеживать все ли впорядке с первым. Если я не прав и у тебя и так все поднимается в докере то просто резолви

2023-04-23 12:01 UTC, eseoa commented on product-service/src/test/java/com/yandex/market/productservice/ProductControllerModuleTest.java
> +class ProductControllerModuleTest {
Ну это нужно если ты решил плотненько сесть за тесты на продукт сервисе, если тесты просто чтобы ci пройти, то резолви

2023-04-25 15:30 UTC, JSON-5tatham commented on product-service/build.gradle
> +    testImplementation 'org.springframework.security:spring-security-test'
давай через либсы

2023-04-25 15:31 UTC, ILikeGson commented on product-service/src/main/java/com/yandex/market/productservice/service/Validator.java
> +        // временно не работает пока нет данных с хатактеристикам по данным
не очень понятно что это?

2023-04-25 15:32 UTC, ILikeGson commented on product-service/src/test/java/com/yandex/market/productservice/ProductControllerModuleTest.java
> +@SqlGroup({
Надо стараться упрощать код тестов, аннотации @SQL во многих ситуациях не нужны и легко заменяются init ом для нужного тест контейнера

2023-04-25 15:34 UTC, JSON-5tatham commented on product-service/src/test/java/com/yandex/market/productservice/ProductControllerModuleTest.java
> +    private final String PATH_TO_MINIMAL_PRODUCT = "src/test/resources/json/create_product_with_minimal.json";
пути сокращаются до /json/....

2023-04-25 15:39 UTC, JSON-5tatham commented on product-service/src/test/java/com/yandex/market/productservice/ProductControllerModuleTest.java
> +        ProductTest product = serviceTest.getProduct(PRODUCT_PATH, REAL_SELLER_ID, productId, status().isOk());
serviceTest усложняет чтение.
да и в целом по всему классу можно сказать, что он перегружен какой информацией. 
Апишный тест - это тест, который имитирует поведение пользователя, когда он использует, например, постман.
Я делаю 1 один запрос с какими то данными и получаю что то в ответ и мне нужно лишь сравнить - я получил то, что хотел или нет.
Здесь этого нет

2023-04-25 15:41 UTC, JSON-5tatham commented on product-service/src/test/java/com/yandex/market/productservice/ProductControllerModuleTest.java
> +        assertAll(
обычно в апишных тестах Assertions даже и не нужны - все проверяется через ResultMatcher, которые используется в andExpect() методе

2023-04-25 15:41 UTC, JSON-5tatham commented on product-service/src/test/java/com/yandex/market/productservice/models/ProductTest.java
> +public record ProductTest(
зачем эти модели здесь?

2023-04-25 15:41 UTC, JSON-5tatham commented on product-service/src/test/java/com/yandex/market/productservice/models/ProductTest.java
> +public record ProductTest(
сорри, дтошки

2023-04-25 15:48 UTC, DameerGamlet commented on product-service/src/main/java/com/yandex/market/productservice/service/Validator.java
> +        // временно не работает пока нет данных с хатактеристикам по данным
Смотри, все характеристики удалили и тесты соотвественно не работали. Сейчас верну и исправлю

2023-04-25 15:57 UTC, DameerGamlet commented on product-service/src/test/java/com/yandex/market/productservice/ProductControllerModuleTest.java
> +@SqlGroup({
Я не использую её только при создании продукта, итого в 2-3х тестах из 20+ возможных в будущем. Из-за этого мне надо её пометить остальные 17+ методов одной и той же аннотацией. 

Неужели оно того стоит?

2023-04-25 16:01 UTC, DameerGamlet commented on product-service/src/test/java/com/yandex/market/productservice/ProductControllerModuleTest.java
> +@SqlGroup({
![image](https://user-images.githubusercontent.com/74682814/234335622-d341abf8-25d2-4132-85fb-bb0c6d7e19d9.png)
Да, вспомнил почему я избавился от этой затеию

2023-04-25 16:17 UTC, DameerGamlet commented on product-service/src/test/java/com/yandex/market/productservice/ProductControllerModuleTest.java
> +    private final String PATH_TO_MINIMAL_PRODUCT = "src/test/resources/json/create_product_with_minimal.json";
![image](https://user-images.githubusercontent.com/74682814/234339469-a3cd1501-6d7e-4a98-9db3-6db8f44f1663.png)
Хмм, кажется что нет

2023-04-25 16:34 UTC, DameerGamlet commented on product-service/src/test/java/com/yandex/market/productservice/ProductControllerModuleTest.java
> +        ProductTest product = serviceTest.getProduct(PRODUCT_PATH, REAL_SELLER_ID, productId, status().isOk());
Хорошо, избавился от него

2023-04-25 20:44 UTC, JSON-5tatham commented on product-service/src/test/java/com/yandex/market/productservice/ProductControllerModuleTest.java
> +    private final String PATH_TO_MINIMAL_PRODUCT = "src/test/resources/json/create_product_with_minimal.json";
А как ты достаешь ресурс? 
у меня проблем не было)

2023-04-26 11:18 UTC, DameerGamlet commented on product-service/src/test/java/com/yandex/market/productservice/ProductControllerModuleTest.java
> +    private final String PATH_TO_MINIMAL_PRODUCT = "src/test/resources/json/create_product_with_minimal.json";
.content(Files.readString(Path.of(MIN_PRODUCT_PATH))))

2023-04-26 11:20 UTC, DameerGamlet commented on product-service/src/test/java/com/yandex/market/productservice/ProductControllerModuleTest.java
> +@SqlGroup({
У меня SQL не используется только создание продукта. Все остальные методы их требуют.
Получается на каждый метод +5 строк.

2023-04-26 15:48 UTC, AlekseiZhi commented on product-service/src/test/java/com/yandex/market/productservice/ProductControllerModuleTest.java
> +    void shouldCreateProductWithMaximal() throws Exception {
почему обновление, если метод create?

2023-04-26 15:50 UTC, AlekseiZhi approved these changes

2023-04-26 21:25 UTC, eseoa approved these changes

2023-04-27 05:24 UTC, AskarovFarkhad reviewed
Хорош!

2023-04-27 09:10 UTC, AskarovFarkhad approved these changes

2023-04-27 09:11 UTC, AskarovFarkhad commented
> А где сами тесты?

2023-04-27 10:28 UTC, merged