Грамотное сообщение если у пользователя нет доступа к ресурсу
splendid-pdf/yandex-market pull request #166
Opened 2023-05-02 09:03 UTC by DameerGamlet

Результатом задачи является вывод сообщения пользователю о том, что у него отсутствует доступ к запрашиваемому ресурсу.

2023-05-05 15:27 UTC, JSON-5tatham requested changes

2023-05-05 15:27 UTC, JSON-5tatham commented on basket-service/src/main/java/com/yandex/market/basketservice/config/SecurityConfig.java
> +                        ((request, response, exception) -> {
А теперь надо посмотреть на контракт и понять свою ошибку!
Ну и еще будет полезно обратить внимание, что логика обработчика копипастится

2023-05-06 19:37 UTC, DameerGamlet commented on basket-service/src/main/java/com/yandex/market/basketservice/config/SecurityConfig.java
> +                        ((request, response, exception) -> {
"А теперь надо посмотреть на контракт и понять свою ошибку!" - в контракте не указана ошибка с статусом 403.

Могу предположить что ты имеешь в виду добавление timestamp, path, requestId и exception/

Исправил доработав к следующему варианту:
![image](https://user-images.githubusercontent.com/74682814/236643013-d23fc59e-86fe-46b0-987c-365e3181829d.png)

2023-05-07 17:00 UTC, AlekseiZhi commented on basket-service/src/main/java/com/yandex/market/basketservice/config/SecurityConfig.java
> +                        ((request, response, exception) -> {
я думаю имеется в виду посмотреть на контракт, который описывал Аркадий в опенапи и посмотреть на вид ошибки, который мы там указали. и если хотим сделать что-то свое это надо согласовать и описать в контракте

2023-06-01 18:13 UTC, closed without merging