Added the ability to view branches by externalId Shop System
splendid-pdf/yandex-market pull request #18
Opened 2022-12-24 16:58 UTC by DameerGamlet

Added the ability to view branches by externalId Shop System

2022-12-24 17:30 UTC, senioricus-patronicus commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/controllers/branch/BranchController.java
> +    @GetMapping("/by-shop-system/{externalId}")
шо это за урл такой веселый

2022-12-24 17:31 UTC, senioricus-patronicus commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/controllers/branch/BranchController.java
> +        return branchService.getAllBranchesByShopSystem(externalId);
getBranchesByShopSystemExternalId

2022-12-24 17:33 UTC, senioricus-patronicus commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/repositories/BranchRepository.java
> +    List<Branch> findAllByShopSystem(UUID externalId);
ждем Pageable в параметры и возвращения Page<Branch> либо сразу превращать в дтошку будет?
Нам неверно надо обсудить, какое представление бранчи ждет клиент от нас - попробую накидать и скину в ближайшее время, обсудим что добавить, что убрать

2022-12-24 17:34 UTC, senioricus-patronicus commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/service/branch/impl/BranchServiceImpl.java
> +        Page<Branch> branches = new PageImpl<>(repository.findAllByShopSystem(externalId));
хитро хитро, но не то)

2022-12-24 18:32 UTC, DameerGamlet commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/service/branch/impl/BranchServiceImpl.java
> +        Page<Branch> branches = new PageImpl<>(repository.findAllByShopSystem(externalId));
Хорошо, буду думать

2022-12-24 18:32 UTC, DameerGamlet commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/controllers/branch/BranchController.java
> +        return branchService.getAllBranchesByShopSystem(externalId);
Да, проглядел

2022-12-24 18:35 UTC, DameerGamlet commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/controllers/branch/BranchController.java
> +    @GetMapping("/by-shop-system/{externalId}")
Ну не можем же мы просто передать id shopа. Идей мало: /find-by-shop-system/, /search/shop-id/ ...

2022-12-24 18:35 UTC, DameerGamlet commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/controllers/branch/BranchController.java
> +    @GetMapping("/by-shop-system/{externalId}")
Надо будет подумать

2022-12-24 18:36 UTC, DameerGamlet commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/repositories/BranchRepository.java
> +    List<Branch> findAllByShopSystem(UUID externalId);
Хорошо

2022-12-24 18:36 UTC, DameerGamlet commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/repositories/BranchRepository.java
> +    List<Branch> findAllByShopSystem(UUID externalId);
Хотя и так всё возращать как и планируется

2022-12-24 19:10 UTC, seniorio-batonio commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/controllers/branch/BranchController.java
> +    @GetMapping("/by-shop-system/{externalId}")
Если речь получить бранч по айдишники шопсистемы - это нереально, т.к. у шопсистемы много бранчей может быть. 
Тогда остается вариант получение бранча по айдишника бранчи, а с этим проблем быть не должно

2022-12-29 05:34 UTC, AskarovFarkhad approved these changes
2 момента глянь пж)

2022-12-29 05:34 UTC, AskarovFarkhad commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/service/branch/impl/BranchServiceImpl.java
> +        System.out.println(branches);
Здесь sout нужен или забыл? Если нужна инфа может завернуть в логирование info?

2022-12-29 05:34 UTC, AskarovFarkhad commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/util/ShopSystemMapper.java
> +        return BranchResponseDto.builder()
BranchResponseDto, ShopSystemBranchInfoDto создать не забыл?) Что-то я их не нашел нигде..

2022-12-29 09:28 UTC, DameerGamlet commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/service/branch/impl/BranchServiceImpl.java
> +        System.out.println(branches);
нет, издержки тестирования

2022-12-29 09:29 UTC, DameerGamlet commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/service/branch/impl/BranchServiceImpl.java
> +        System.out.println(branches);
убираю

2022-12-29 09:30 UTC, DameerGamlet commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/util/ShopSystemMapper.java
> +        return BranchResponseDto.builder()
BranchResponseDto - вот же возвращается в качестве ответа, а ShopSystemBranchInfoDto передаётся в качестве аргумента

2022-12-29 09:30 UTC, DameerGamlet commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/util/ShopSystemMapper.java
> +        return BranchResponseDto.builder()
Или ты про что?

2022-12-29 09:31 UTC, DameerGamlet commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/util/ShopSystemMapper.java
> +        return BranchResponseDto.builder()
А, неужели не всё запушилось

2022-12-30 07:01 UTC, AskarovFarkhad commented
Ок

2022-12-30 17:15 UTC, seniorio-batonio commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/controllers/branch/BranchController.java
> +    public Page<BranchResponseDto> getAllBranchesByShopSystem(@PageableDefault(size = 20) Pageable pageable,
...ByShopSystemId наверно имелось в виду?

2022-12-30 17:16 UTC, seniorio-batonio commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/dto/branch/BranchResponseDto.java
> +    private String branchName;
Интересно, зачем валидировать респонс - мы не доверяем сервисами или своей базе?)

2022-12-30 17:17 UTC, seniorio-batonio commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/repositories/BranchRepository.java
> +    Page<Branch> findAllByShopSystem(@Param("externalId") UUID externalId,
...ByShopSystemId или ...ByShopSystemExternalId

2022-12-30 17:18 UTC, seniorio-batonio commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/service/branch/impl/BranchServiceImpl.java
>          branch.setShopSystem(shopSystemService.getShopSystemByExternalId(dto.getShopSystem()));
у нас есть хелпер методы в шопсистем ентити для добавления бранчей

2022-12-30 19:45 UTC, DameerGamlet commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/controllers/branch/BranchController.java
> +    public Page<BranchResponseDto> getAllBranchesByShopSystem(@PageableDefault(size = 20) Pageable pageable,
Да, верно

2022-12-30 19:46 UTC, DameerGamlet commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/repositories/BranchRepository.java
> +    Page<Branch> findAllByShopSystem(@Param("externalId") UUID externalId,
Мне второе кажется более информативнее, сейчас сделаю

2022-12-30 19:47 UTC, DameerGamlet commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/dto/branch/BranchResponseDto.java
> +    private String branchName;
Точно, я взял с аргумента оригинала, исправляю

2022-12-30 19:49 UTC, DameerGamlet commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/controllers/branch/BranchController.java
> +    public Page<BranchResponseDto> getAllBranchesByShopSystem(@PageableDefault(size = 20) Pageable pageable,
getAllBranchesByShopSystemExternalId мне кажется более информативным именем

2022-12-30 19:54 UTC, DameerGamlet commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/service/branch/impl/BranchServiceImpl.java
>          branch.setShopSystem(shopSystemService.getShopSystemByExternalId(dto.getShopSystem()));
Я правильно понял что ты имеешь в виду этот метод?

2022-12-30 19:55 UTC, DameerGamlet commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/service/branch/impl/BranchServiceImpl.java
>          branch.setShopSystem(shopSystemService.getShopSystemByExternalId(dto.getShopSystem()));
Я только не понял как это может помочь добавить в бранч шоп систему (shop_system_id = ххх)

2023-01-06 15:49 UTC, seniorio-batonio commented on .github/workflows/build-action.yaml
> +      - develop/shopsystem
Зачем?
было настроено на весь проект

2023-01-06 15:51 UTC, seniorio-batonio commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/dto/branch/BranchResponseDto.java
> +    private String token;
response dto не совпадает с тем, что на миро доске)
Деливери ентити возвращать не будем, нужна дто) Больше дто Богу дто

2023-01-06 15:57 UTC, seniorio-batonio commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/service/branch/impl/BranchServiceImpl.java
> +        return new PageImpl<>(
new PageImpl выглядит не по феншую, что думаешь. Метод бы для этого

2023-01-06 16:02 UTC, seniorio-batonio requested changes
Исправить дтошки, файл конфигурации CI

2023-01-07 14:00 UTC, DameerGamlet commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/service/branch/impl/BranchServiceImpl.java
> +        return new PageImpl<>(
Да, это можно сделать

2023-01-08 07:23 UTC, DameerGamlet commented on .github/workflows/build-action.yaml
> +      - develop/shopsystem
Build.action не выполнялся, если задействовались все проекты. Понял, что не стоило трогать)

2023-01-10 20:17 UTC, seniorio-batonio commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/controllers/shop/ShopSystemController.java
> +    @GetMapping("/{externalId}/branches")
Ресурс жи branches, этом эндпоинту место в BranchController

2023-01-10 20:18 UTC, seniorio-batonio commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/controllers/shop/ShopSystemController.java
> +        log.info("Received a request to get paginated list of branches by shop systems.");
В логах даже айдишника нет, грусть печаль

2023-01-10 20:20 UTC, seniorio-batonio commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/dto/branch/BranchResponseDto.java
> +    private Set<SpecialOffer> discounts = new HashSet<>();
в json'е на миро точно нет никаких SpecialOffer

2023-01-10 20:20 UTC, seniorio-batonio commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/dto/branch/DeliveryResponseDto.java
> +    private Set<@Valid DeliveryZoneDto> deliveryZones = new HashSet<>();
А @Valid зачем?

2023-01-10 20:22 UTC, seniorio-batonio commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/service/branch/impl/BranchServiceImpl.java
> +        ShopSystem shopSystem = shopSystemService.getShopSystemByExternalId(dto.getShopSystem());
dto.getShopSystem() - неочевидно, что речь идет об externalId

2023-01-10 20:23 UTC, seniorio-batonio commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/service/branch/impl/BranchServiceImpl.java
> +        ShopSystemBranchInfoDto shopSystemInfoForBranch = shopSystemService
три похода в базу? 
А за один не управимся?

2023-01-10 20:25 UTC, seniorio-batonio commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/service/branch/impl/BranchServiceImpl.java
> +    public Page<BranchResponseDto> getBranchesByShopSystem(UUID externalId, Pageable pageable) {
тут и ниже в getBranchPageImpl происходит что то странное)
Вы напугали деда)

2023-01-11 10:56 UTC, DameerGamlet commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/controllers/shop/ShopSystemController.java
> +    @GetMapping("/{externalId}/branches")
http://localhost:8080/public/api/v1/shopsystems/a30b9021-6a5b-44d7-9f99-9a770a7eae3c/branches

2023-01-14 10:09 UTC, seniorio-batonio commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/dto/branch/DeliveryResponseDto.java
> +    private Set<PickupPointPartner> pickupPointPartners = new HashSet<>();
Dto будет меняться или она value-based?
Инициализация сетов тут не нужна

2023-01-14 10:12 UTC, seniorio-batonio commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/repositories/BranchRepository.java
> +    @Query(value = "SELECT " +
в java 17 появились фичи для строк

2023-01-14 10:17 UTC, seniorio-batonio commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/service/branch/impl/BranchServiceImpl.java
> +        branch.setDelivery(mapper.toDeliveryFromDto(dto.getDelivery()));
С мапперами еще не разобрались?

2023-01-16 11:02 UTC, DameerGamlet commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/service/branch/impl/BranchServiceImpl.java
> +        branch.setDelivery(mapper.toDeliveryFromDto(dto.getDelivery()));
Кто-то обещал добавить, но что-то пока не видно

2023-01-16 20:47 UTC, seniorio-batonio commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/controllers/branch/BranchController.java
> +    @RequestMapping(value = "/shopsystems/{externalId}/branches", method = RequestMethod.GET)
решил через @RequestMapping потренироваться?))

2023-01-16 20:48 UTC, seniorio-batonio commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/dto/branch/DeliveryResponseDto.java
> +    private Set<PickupPointPartner> pickupPointPartners = new HashSet<>();
все еще висит

2023-01-16 20:50 UTC, seniorio-batonio commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/repositories/BranchRepository.java
> +    Optional<BranchResponseProjection> getBranchResponseByExternalid(@Param("externalId") UUID externalId);
да всё проще пишется и + через JPQL)

2023-01-17 12:19 UTC, DameerGamlet commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/repositories/BranchRepository.java
> +    Optional<BranchResponseProjection> getBranchResponseByExternalid(@Param("externalId") UUID externalId);
Не залились исправления

2023-01-17 12:20 UTC, DameerGamlet commented on shopsystem-service/src/main/java/com/yandex/market/shopservice/dto/branch/DeliveryResponseDto.java
> +    private Set<PickupPointPartner> pickupPointPartners = new HashSet<>();
не залились изменения

2023-02-02 08:03 UTC, closed without merging