Add user-info validation & user-info exceptions handler & add migrations
splendid-pdf/yandex-market pull request #22
Opened 2022-12-30 19:33 UTC by NikPrg

Add validation for all Dto's fields.
Add update migrations.
Add exception handler.

2022-12-30 19:37 UTC, DVKolm commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/repository/UserRepository.java
>      boolean existsByEmail(String email);
Добавь аннотацию Query

2022-12-30 19:37 UTC, NikPrg commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/repository/UserRepository.java
>      boolean existsByEmail(String email);
зорошо

2022-12-30 19:41 UTC, seniorio-batonio commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/repository/UserRepository.java
>      boolean existsByEmail(String email);
а зачем?

2022-12-30 19:46 UTC, DVKolm commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/repository/UserRepository.java
>      boolean existsByEmail(String email);
так быстрее

2022-12-30 19:51 UTC, seniorio-batonio requested changes

2022-12-30 19:51 UTC, seniorio-batonio commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/controller/UserController.java
> +        log.info("Received request to delete a user: {}", externalId);
...to delete a user by externalId ....

2022-12-30 19:51 UTC, seniorio-batonio commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/controller/UserInfoExceptionHandler.java
> +    //TODO: should we use a RuntimeException???
а RuntimeException ?

2022-12-30 19:51 UTC, seniorio-batonio commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/repository/UserRepository.java
> +    Optional<User> findUserByEmailOrPhone(String value);
поиск не выглядит эффективным

2022-12-30 19:51 UTC, seniorio-batonio commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/service/UserService.java
> +        return userMapper.mapToResponseDto(userRepository.findUserByEmailOrPhone(emailOrPhone)
ну так надо же выяснить что перед Вами, телефон или емайл для оптимизации запроса

2022-12-30 19:51 UTC, seniorio-batonio commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/validator/UserDtoFieldValidator.java
> +public interface UserDtoFieldValidator {
FieldValidator типизированный T был бы лучше.
Но Вам виднее

2022-12-30 19:51 UTC, seniorio-batonio commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/validator/UserDtoValidator.java
> +        List<String> exceptions = new ArrayList<>();
это не exceptions)

2022-12-30 19:51 UTC, seniorio-batonio commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/validator/impl/BirthdayUserDtoFieldValidatorImpl.java
> +        if (StringUtils.isBlank(userRequestDto.getBirthday().toString())) {
а если userRequestDto.getBirthday() is null?

2022-12-30 19:51 UTC, seniorio-batonio commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/validator/impl/BirthdayUserDtoFieldValidatorImpl.java
> +        } else if (userRequestDto.getBirthday().toString().matches("[12]\\\\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\\\d|3[01])")) {
неэффективно Pattern matching

2022-12-30 19:51 UTC, seniorio-batonio commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/validator/impl/EmailUserDtoFieldValidatorImpl.java
> +        } else if (!userRequestDto.getEmail().matches("^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$")) {
тоже

2022-12-30 19:51 UTC, seniorio-batonio commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/validator/impl/PhoneUserDtoFieldValidatorImpl.java
> +        if (!phoneNumber.matches(REG_VALID_PHONE)) {
не верю этому валидатору, выглядит так, что я могу прислать вообще практически что угодно

2022-12-30 19:51 UTC, seniorio-batonio commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/validator/impl/SexUserDtoFieldValidatorImpl.java
> +        if (!EnumUtils.isValidEnum(UserRequestDto.SexEnum.class, userRequestDto.getSex().toString())) {
А если userRequestDto.getSex() is null

2022-12-30 19:51 UTC, seniorio-batonio commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/repository/UserRepository.java
>      boolean existsByEmail(String email);
а где доказательства)

2022-12-31 12:51 UTC, DameerGamlet commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/validator/impl/BirthdayUserDtoFieldValidatorImpl.java
> +        } else if (userRequestDto.getBirthday().toString().matches("[12]\\\\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\\\d|3[01])")) {
Может стоит повесить на поле в юзерсе?
И подумать над возможностью заменить на @DateTimeFormat(pattern = "dd/MM/yyyy"), но уже с другими параметрами

2022-12-31 13:17 UTC, DameerGamlet approved these changes

2022-12-31 13:17 UTC, DameerGamlet commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/controller/UserController.java
>      @Override
@ResponseStatus(HttpStatus.CREATED)
А ResponseEntity убрать вовсе
public UUID createUser(UserRequestDto userRequestDto) {
...
return userService.createUser(userRequestDto);
}

2022-12-31 13:17 UTC, DameerGamlet commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/controller/UserInfoExceptionHandler.java
> +public class UserInfoExceptionHandler {
Что это делает в папке с контроллером?
И вроде как договаривались в общий для всех сервисов его выводить GlobalExceptionHandler

2022-12-31 13:17 UTC, DameerGamlet commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/validator/impl/BirthdayUserDtoFieldValidatorImpl.java
> +            exceptions.add("Incorrect format birthday");
Повесить бы на поле в UserRequestDto над полем birthDay аннотацию валидации и убрать вот это все.
Например, @DateTimeFormat(pattern = "dd/MM/yyyy", message = "Incorrect format birthday")

2022-12-31 13:17 UTC, DameerGamlet commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/validator/impl/EmailUserDtoFieldValidatorImpl.java
> +        } else if (!userRequestDto.getEmail().matches("^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$")) {
Также аннотация @Email заменяет это всё

2022-12-31 13:17 UTC, DameerGamlet commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/validator/impl/EmailUserDtoFieldValidatorImpl.java
> +        } else if (!userRequestDto.getEmail().matches("^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$")) {
Будет вот так:
 @Email(message = "\"Email\" field should be valid")

2022-12-31 13:17 UTC, DameerGamlet commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/validator/impl/EmailUserDtoFieldValidatorImpl.java
> +        if (StringUtils.isBlank(userRequestDto.getEmail())) {
Это легко заменяется эти
        @ NotBlank(message = "\"Email\" field must not be empty")
        String email

2022-12-31 13:17 UTC, DameerGamlet commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/validator/impl/NameUserDtoFieldValidatorImpl.java
> +        if (StringUtils.isBlank(userRequestDto.getFirstName())) {
@ NotBlank(message = "\"First Name\" field must not be empty")
        String firstName

2022-12-31 13:17 UTC, DameerGamlet commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/validator/impl/NameUserDtoFieldValidatorImpl.java
> +        if (StringUtils.isBlank(userRequestDto.getFirstName())) {
Всё это сделать во втором случае

2022-12-31 13:17 UTC, DameerGamlet commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/validator/impl/PasswordUserDtoFieldValidatorImpl.java
> +        if (StringUtils.isBlank(userRequestDto.getPassword())) {
@ NotBlank(message = "\"Password\" field must not be empty")

2022-12-31 13:17 UTC, DameerGamlet commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/validator/impl/PhoneUserDtoFieldValidatorImpl.java
> +        if (!phoneNumber.matches(REG_VALID_PHONE)) {
Примерный валидатор через аннотацию:
@Pattern(regexp = "^(\\+7|8)[\\s(]*\\d{3,4}[)\\s]*\\d{2,3}[\\s-]?\\d{2}[\\s-]?\\d{2}$",
                message = "Invalid \"Phone number\" entered")

2022-12-31 13:17 UTC, DameerGamlet commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/validator/impl/PhoneUserDtoFieldValidatorImpl.java
> +            exceptions.add("Incorrect format for number");
for phone number

2022-12-31 13:17 UTC, DameerGamlet commented on user-info-service/src/main/resources/application.yaml
>      username: ${postgres_user}
Согласно стандартам надо делать db_name, postgres_user, postgres_password и большими буквами  DB_NAME, POSTGRES_USER, POSTGRES_PASSWORD

2022-12-31 13:17 UTC, DameerGamlet commented on user-info-service/src/main/resources/application.yaml
>      username: ${postgres_user}
Предполагается что это переменные, которые никак не должны меняться во время выполнения работы, следовательно, константа и именовывается согласно этому в высоком регистре

2023-01-01 19:49 UTC, NikPrg commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/validator/impl/BirthdayUserDtoFieldValidatorImpl.java
> +        if (StringUtils.isBlank(userRequestDto.getBirthday().toString())) {
![image](https://user-images.githubusercontent.com/98475612/210183039-61e99d39-5ac5-46ba-a49c-07b6e4367c35.png)
![изображение_2023-01-01_224736041](https://user-images.githubusercontent.com/98475612/210183042-149f3bc1-4eba-4d35-84ed-bb9f6af92cd8.png)

2023-01-01 19:50 UTC, NikPrg commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/validator/impl/BirthdayUserDtoFieldValidatorImpl.java
> +        if (StringUtils.isBlank(userRequestDto.getBirthday().toString())) {
Получается, что он проверяет не только на пустоту, но ещё и на null
Поэтому, всё будет окей

2023-01-01 19:51 UTC, NikPrg commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/repository/UserRepository.java
> +    Optional<User> findUserByEmailOrPhone(String value);
будем думать)

2023-01-01 19:52 UTC, NikPrg commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/controller/UserController.java
> +        log.info("Received request to delete a user: {}", externalId);
ок, будет исправлено

2023-01-01 19:59 UTC, seniorio-batonio commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/validator/impl/BirthdayUserDtoFieldValidatorImpl.java
> +        if (StringUtils.isBlank(userRequestDto.getBirthday().toString())) {
еще раз давай подумаем, если userRequestDto.getBirthday() == null
то userRequestDto.getBirthday().toString() вызывает NPE

2023-01-01 20:27 UTC, seniorio-batonio commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/validator/impl/EmailUserDtoFieldValidatorImpl.java
> +        } else if (!userRequestDto.getEmail().matches("^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$")) {
Дамир, мы опен апи модель используем

2023-01-01 21:05 UTC, NikPrg commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/validator/impl/BirthdayUserDtoFieldValidatorImpl.java
> +        if (StringUtils.isBlank(userRequestDto.getBirthday().toString())) {
![image](https://user-images.githubusercontent.com/98475612/210184509-ff66cb28-32b5-49d4-88fc-8926b090dfbb.png)
Понимаю, что это костыль, понимаю, что у нас два раза будет происходить проверка на null. Однако, я не думаю, что будут возникать какие-то траблы с перфомансом из-за доп проверки на null, imho

2023-01-02 11:37 UTC, DameerGamlet commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/validator/impl/EmailUserDtoFieldValidatorImpl.java
> +        } else if (!userRequestDto.getEmail().matches("^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$")) {
Хорошо

2023-01-02 12:00 UTC, NikPrg commented on user-info-service/build.gradle
> +    implementation 'org.flywaydb:flyway-core:9.10.2'
Принял

2023-01-02 12:20 UTC, NikPrg commented on user-info-service/src/main/java/com/yandex/market/userinfoservice/validator/UserDtoValidator.java
> +        List<String> exceptions = new ArrayList<>();
У нас есть единственная exception, которую мы выбрасываем(ValidationException).
Для неё мы собираем лист сообщений, в котором будет лежать инфа о месте-(х) где пользователь допустил ошибки.
Следовательно, стоит назвать этот лист: **exceptionMessages**

2023-01-03 21:30 UTC, seniorio-batonio approved these changes

2023-01-04 16:28 UTC, merged