Feature/delete and visible product ids by seller
splendid-pdf/yandex-market pull request #73
Opened 2023-02-22 10:49 UTC by DameerGamlet

При нажатии на кнопку:

- “в архив выбранные”,
- “достать выбранное из архива,“
- “снять с продажи выбранное“,
- “вернуть в продажу выбранное“.

В списке товаров селлера, со списком товаров происходят соответствующие действия ( меняется 1 флажок в базе данных )

ПРИМЕРЫ СОБЫТИЙ НА ФРОНТЕ:

- deletionParams = <DELETE, true> - удаление
- deletionParams = <DELETE, false> - вернуть с архива
- deletionParams = <VISIBLE, true> - сделать видимым
- deletionParams = <VISIBLE, false> - сделать невидимым

ПРИМЕР ЗАПРОСА:
Действие: Вернуть товар на продажу

PATCH http://localhost:9090/public/api/v1/sellers/301c5370-be41-421e-9b15-f1e80a7074f2/products?method=VISIBLE&methodAction=true

Content-Type: application/json

[
  "301c5370-be41-421e-9b15-f1e80a7074f5",
  "301c5370-be41-421e-9b15-f1e80a7074f7"
]

2023-02-24 15:08 UTC, DameerGamlet commented
@DameerGamlet
[Removing product(s) from the archive for a specific seller](https://github.com/splendid-pdf/yandex-market/pull/73/commits/45417d66b3cf45816de0efb5582ad60d94a8c14f) - этот коммит от другой стори. Удалено!

2023-02-28 13:43 UTC, eseoa commented on product-service/src/main/java/com/yandex/market/productservice/controller/SellerController.java
> +        }
я думаю из контроллера 55-73 строчки лучше перенести в сервис. Попробуй как-нибудь иначе иф элсы расписать, вот пункт 3.2 глянь мб поможет, если нет, то забей и оставь иф элсы как есть.
https://www.baeldung.com/java-replace-if-statements

Убери пока везде логгирование, вместе с ним уйдет и переменная methodName

2023-02-28 13:55 UTC, eseoa requested changes
Может тут еще что - то есть, но я критичного не заметил чего - то. Логги пока точно убери

2023-02-28 13:55 UTC, eseoa commented on product-service/src/main/java/com/yandex/market/productservice/config/SpringdocConfig.java
> +}
если этот класс убрать что - нибудь изменится ? Если да, можешь плиз написать что именно и просто резолви

2023-03-01 10:02 UTC, eseoa approved these changes

2023-03-01 10:03 UTC, eseoa approved these changes

2023-03-01 10:35 UTC, AlekseiZhi approved these changes

2023-03-01 13:10 UTC, merged