add new seller product
splendid-pdf/yandex-market pull request #75
Opened 2023-02-24 14:29 UTC by AlekseiZhi

2023-02-24 16:24 UTC, DameerGamlet commented on order-service/src/main/java/com/yandex/market/orderservice/dto/OrderRequestDto.java
>          LocalDateTime creationTimestamp,
Дату мне кажется не стоит передавать в requestDto

2023-02-24 16:24 UTC, DameerGamlet commented on order-service/src/main/java/com/yandex/market/orderservice/dto/OrderRequestDto.java
>          LocalDateTime creationTimestamp,
Для этого можно использовать аннотацию:
@CreationTimestamp
    private LocalDateTime createdDate;

И данное поле само будет создаваться на текущую дату

Для обновления используется:
@UpdateTimestamp
    private LocalDateTime updatedDate;

2023-02-24 16:24 UTC, DameerGamlet commented on order-service/src/main/java/com/yandex/market/orderservice/dto/OrderRequestDto.java
>          LocalDateTime creationTimestamp,
paymentDateTime и creationTimestamp чем отличаются? (какая роль каждого из них?)

2023-02-24 16:24 UTC, DameerGamlet commented on product-service/build.gradle
> +    //implementation "org.flywaydb:flyway-core:${flywayCoreVersion}"
Аннотацию не комменть. Тебе надо в application.yml flyway поставить в false

2023-02-24 16:24 UTC, DameerGamlet commented on product-service/build.gradle
> +    //implementation "org.flywaydb:flyway-core:${flywayCoreVersion}"
flyway:
    enabled: false

Вот так

2023-02-24 16:24 UTC, DameerGamlet commented on product-service/src/main/java/com/yandex/market/productservice/dto/ProductRequestDto.java
> +        boolean isVisible,
предлагаю на вверх ставить наиболее используемые и важные поля, такие как имя, цена, тип и т.д. Я как вижу, самое последнее - это даты, предпоследние булеаны и т.д.

2023-02-24 16:24 UTC, DameerGamlet commented on product-service/src/main/java/com/yandex/market/productservice/dto/ProductSpecialPriceDto.java
> +        LocalDateTime specialPriceFromDate,
Такое чувство что поле specialPriceFromDate может быть не только FutureOrPresent. Например, я выложил товар на который уже специальная акция (которая появилась 3 дня назад). Но моём сайте у товара скидка с 20 по 27 (а сегодня, например, 24), но в нашем маркетплейсе он может установить только с 24 по 27

2023-02-24 16:24 UTC, DameerGamlet commented on product-service/src/main/java/com/yandex/market/productservice/dto/ProductSpecialPriceDto.java
> +        LocalDateTime specialPriceFromDate,
Мне кажется это немногим неправильным. Либо поставить  @PastOrPresent либо вообще не покрывать аннотации, либо оставить всё, как есть (если это согласно требованиям ПМ)

2023-02-24 16:24 UTC, DameerGamlet commented on product-service/src/main/java/com/yandex/market/productservice/mapper/ProductMapper.java
> +        uses = {ProductCharacteristicMapper.class, ProductImageMapper.class, ProductSpecialPriceMapper.class, TypeMapper.class}
Хотел бы попросить добавить поле unmappedTargetPolicy = ReportingPolicy.IGNORE, так как в дальнейшем он будет в тестах ругаться (кидать варнинги)

2023-02-24 16:24 UTC, DameerGamlet commented on product-service/src/main/java/com/yandex/market/productservice/mapper/ProductMapper.java
>      @Mapping(target = "isVisible", defaultValue = "true")
При создании товар должен быть невидим (isVisible = false). Вроде именно так говорили так как можно создать товар не указывая цены или количества

2023-02-24 16:24 UTC, DameerGamlet commented on product-service/src/main/java/com/yandex/market/productservice/mapper/ProductMapper.java
>      @Mapping(target = "isVisible", defaultValue = "true")
Этот момент надо у Серёги узнать

2023-02-24 16:24 UTC, DameerGamlet commented on product-service/src/main/java/com/yandex/market/productservice/mapper/ProductMapper.java
> +    @Mapping(target = "articleNumber", expression = "java(UUID.randomUUID())")
вроде как говорили articleNumber будет 8 (или около того) значное уникальное число из цифр и чисел. Артикул должен быть уникальным для каждого товара в магазине и легко читаемым для владельца магазина, но с UUID этого тяжело будет добавить.

К тому же предполагается что продавец сам может ввести артикул

2023-02-24 16:24 UTC, DameerGamlet commented on product-service/src/main/java/com/yandex/market/productservice/mapper/ProductMapper.java
> +    @Mapping(target = "externalId", expression = "java(UUID.randomUUID())")
Для этого можно навесить различные аннотация над полем в сущьности Order. Например, так:

   @Column(name = "external_id", columnDefinition = "uuid")
    @GeneratedValue(generator = "UUID")
    @GenericGenerator(name = "UUID", strategy = "org.hibernate.id.UUIDGenerator")
    private UUID externalId;

2023-02-24 16:24 UTC, DameerGamlet commented on product-service/src/main/java/com/yandex/market/productservice/mapper/ProductMapper.java
> +    @Mapping(target = "externalId", expression = "java(UUID.randomUUID())")
Но можно оставить и так, если всем будет удобно (просто у меня на данное поле жаловался маппер, если всем норм, то можно оставить)

2023-02-24 16:24 UTC, DameerGamlet commented on product-service/src/main/java/com/yandex/market/productservice/mapper/ProductMapper.java
> +    @Mapping(target = "externalId", expression = "java(UUID.randomUUID())")
Также можно сделать так:

@PrePersist
    protected void onCreate() {
        this.externalId = UUID.randomUUID();
    }

2023-02-26 08:48 UTC, AlekseiZhi commented on product-service/src/main/java/com/yandex/market/productservice/mapper/ProductMapper.java
> +    @Mapping(target = "externalId", expression = "java(UUID.randomUUID())")
> Для этого можно навесить различные аннотация над полем в сущьности Order. Например, так:
> 
> @column(name = "external_id", columnDefinition = "uuid") @GeneratedValue(generator = "UUID") @GenericGenerator(name = "UUID", strategy = "org.hibernate.id.UUIDGenerator") private UUID externalId;

тут у меня тоже маппер в классе TypeMapper не хотел работать долгое время. но с Аркадием разобрались с ним) expression = "java(java.util.UUID.randomUUID())"

2023-02-26 10:14 UTC, AlekseiZhi commented on product-service/src/main/java/com/yandex/market/productservice/dto/ProductSpecialPriceDto.java
> +        LocalDateTime specialPriceFromDate,
а как может существовать акция на еще не созданный товар?

2023-02-26 10:26 UTC, AlekseiZhi commented on product-service/src/main/java/com/yandex/market/productservice/mapper/ProductMapper.java
> +    @Mapping(target = "articleNumber", expression = "java(UUID.randomUUID())")
это не артикул продавца, артикул продавца поле -  articleFromSeller )

2023-02-26 11:20 UTC, DameerGamlet commented on product-service/src/main/java/com/yandex/market/productservice/dto/ProductSpecialPriceDto.java
> +        LocalDateTime specialPriceFromDate,
Ну если я например уже имею магазин и хочу расширить круг клиентов (почему нет)

2023-02-26 11:24 UTC, DameerGamlet commented on product-service/src/main/java/com/yandex/market/productservice/mapper/ProductMapper.java
> +    @Mapping(target = "articleNumber", expression = "java(UUID.randomUUID())")
Тогда чем он отличается от externalId? Просто не понимаю на кой он тогда нужен

2023-02-26 12:37 UTC, DameerGamlet commented on product-service/src/main/java/com/yandex/market/productservice/controller/ProductController.java
> +//    @PutMapping("{externalId}")
Я бы тут добавил с TODO. раз ты скрыл метод, значит на будущее надо сказать что с ним следует сделать.

Например,
// TODO: метод требует значительные изменения в связи с новой моделью продукта, товар требует иметь продавца

2023-02-26 12:37 UTC, DameerGamlet commented on product-service/src/main/java/com/yandex/market/productservice/controller/ProductController.java
> +//    @PutMapping("{externalId}")
Просто есть скрыли весь метод, значит он в будущем может приходиться или расскоментиться и модернизироваться

2023-02-26 12:37 UTC, DameerGamlet commented on product-service/src/main/java/com/yandex/market/productservice/dto/ProductRequestDto.java
> +        Set<ProductCharacteristicDto> productCharacteristicDto,
А почему @Valid убрали? В ProductCharacteristicDto все поля валидируются

2023-02-26 12:37 UTC, DameerGamlet commented on product-service/src/main/java/com/yandex/market/productservice/dto/ProductRequestDto.java
> +        @NotEmpty
А он точно @notEmpty?

2023-02-27 09:49 UTC, DameerGamlet approved these changes

2023-02-28 14:24 UTC, eseoa requested changes

2023-02-28 14:24 UTC, eseoa commented on product-service/src/main/java/com/yandex/market/productservice/controller/ProductController.java
>          log.info("Received request to create a product by given value: {}", productRequestDto);
логи пока убери, они у нас чуть иначе будут выглядеть

2023-02-28 14:24 UTC, eseoa commented on product-service/src/main/java/com/yandex/market/productservice/model/Characteristic.java
> +    }
Я думаю тут хелпер методы не нужны, но могу быть не прав

2023-02-28 14:24 UTC, eseoa commented on product-service/src/main/java/com/yandex/market/productservice/model/TypeCharacteristic.java
> -}
а что было не так с этим классом, зачем понадобилось менять название ?

2023-02-28 14:24 UTC, eseoa commented on product-service/src/main/java/com/yandex/market/productservice/repository/ProductRepository.java
> +    Product getProductBySellerExternalId(UUID externalId);
если ты писал, то Optional (Product), если не ты, то все равно поменяй )

2023-02-28 17:20 UTC, eseoa approved these changes

2023-02-28 17:21 UTC, merged