Feature/delete full products by seller
splendid-pdf/yandex-market pull request #76
Opened 2023-02-24 15:11 UTC by DameerGamlet

ТЕКСТ ЗАДАЧИ:

При нажатии кнопки “удалить товар” в архиве. Товар полностью удаляется из БД.

УСЛОВИЯ:

Все товары из списка товаров должны уже иметься в БД. Если товар есть в списке (архиве), то он должен передаваться без проблем (в запросе). Товар для удаления должен иметь параметр (isDeleted = true), иначе ничего не делаем.

ПРИМЕР ЗАПРОСА:

DELETE public/api/v1/products/sellers/{sellerExternalId}/products

Content-Type: application/json

[
  "301c5370-be41-421e-9b15-f1e80a7074f5",
  "301c5370-be41-421e-9b15-f1e80a7074f7"
]

ПАРАМЕТРЫ МЕТОДА:

@RequestBody List<UUID> productIds
@PathVariable(value = "sellerId") UUID sellerId

2023-02-27 16:09 UTC, AlekseiZhi approved these changes

2023-02-28 14:04 UTC, eseoa requested changes

2023-02-28 14:04 UTC, eseoa commented on product-service/src/main/java/com/yandex/market/productservice/controller/SellerController.java
> +                                            @RequestBody List<UUID> productIds) {
Помню мы вроде обсуждали это что пусть будет RequestBody, но давай лучше реквест парамом.
Вот тут есть ссылка на документацию почему нельзя передавать тело в делит запросе 
https://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request

Даже сам если попробуешь проверить этот запрос не через постман а например Talend Api, то такой запрос отправить не получиться. 

Вот еще на пост на хабре, где люди над этим рассуждают 
https://qna.habr.com/q/905295

2023-02-28 19:50 UTC, DameerGamlet commented on product-service/src/main/java/com/yandex/market/productservice/controller/SellerController.java
> +                                            @RequestBody List<UUID> productIds) {
Я отправлял запросы через встроенный в IDEA инструмент и довольно успешно. Утром всё исследую и исправлю

2023-03-01 10:02 UTC, eseoa approved these changes

2023-03-01 12:46 UTC, merged