List of products and archive. Swagger integration.
splendid-pdf/yandex-market pull request #77
Opened 2023-02-25 14:33 UTC by DameerGamlet

НА КАКИЕ ДЕЙСТВИЯ РЕАКЦИЯ:

Реагирует на нажатие кнопок:
> Список товаров (товары видимые / невидимые, но не удалённые)
> Архив (товары удалённые (следовательно невидимые))

ВХОДНЫЕ ПАРАМЕТРЫ:

> @PathVariable UUID sellerId,
> @RequestParam VisibleMethod method,
> @PageableDefault(…)Pageable pageable

ПРИМЕР ЗАПРОСА:

GET public/api/v1/sellers/{sellerExternalId}/products?method=NOT_LIMITS

Возможные значения method:

> PRODUCT_LIST -  получить все неудалённые товары (видимые, невидимые, неудалённые);
> ARCHIVE - получить все товары из архива

2023-02-26 20:13 UTC, AlekseiZhi approved these changes

2023-02-28 14:06 UTC, eseoa requested changes

2023-02-28 14:06 UTC, eseoa commented on product-service/src/main/java/com/yandex/market/productservice/config/SpringdocConfig.java
> +}
про конфиг я уже спросил в 73 pr

2023-03-01 10:02 UTC, eseoa approved these changes

2023-03-01 10:05 UTC, merged