Seller information update
splendid-pdf/yandex-market pull request #89
Opened 2023-03-05 18:46 UTC by DameerGamlet

Метод на обновление продавца.
На вход: DTO и externalId.

Сваггер интегрирован.

Тесты: 
> 1) Была изменена вся информация (буквально вся модель меняется кроме ID и externalId). Было проверено что все данные были изменены так, как и ожидалось.
> 2) Было изменено только firstName и lastName/
> 3) На вход был поддан пустой DTO объект (вида: { })

2023-03-05 21:27 UTC, eseoa requested changes

2023-03-05 21:27 UTC, eseoa commented on seller-info-service/src/main/java/com/yandex/market/sellerinfoservice/controller/SellerController.java
> +    public void updateSeller(@PathVariable UUID sellerId, @RequestBody SellerRequestDto sellerRequestDto) {
```suggestion
    public SellerResponseDto updateSeller(@PathVariable UUID sellerId, @RequestBody SellerRequestDto sellerRequestDto) {
```

2023-03-05 21:27 UTC, eseoa commented on seller-info-service/src/main/java/com/yandex/market/sellerinfoservice/repository/SellerRepository.java
> +    Optional<Seller> getSellerByExternalId(UUID sellerExternalId);
если обозвать метод так:
```suggestion
    Optional<Seller> findByExternalId(UUID sellerExternalId);
```
То запрос Query не нужен

2023-03-06 12:02 UTC, eseoa approved these changes

2023-03-06 12:18 UTC, AlekseiZhi approved these changes

2023-03-06 12:45 UTC, merged