add operation delete seller
splendid-pdf/yandex-market pull request #91
Opened 2023-03-06 16:29 UTC by AlekseiZhi

добавлен метод для удаления продавца. описание swagger и тесты

2023-03-07 08:23 UTC, NikPrg requested changes

2023-03-07 08:23 UTC, NikPrg commented on seller-info-service/src/main/java/com/yandex/market/sellerinfoservice/service/impl/SellerServiceImpl.java
> +}
делаешь лишние действия

2023-03-07 15:56 UTC, DameerGamlet commented on seller-info-service/src/main/java/com/yandex/market/sellerinfoservice/controller/SellerController.java
> +            @ApiResponse(description = "Такого продавца не существует", responseCode = "404 ")
`"404 "` > `"404"`

2023-03-07 15:56 UTC, DameerGamlet commented on seller-info-service/src/main/java/com/yandex/market/sellerinfoservice/service/impl/SellerServiceImpl.java
> +        Seller seller = getSellerByExternalId(sellerExternalId);
Можно это сделать в один запрос. Например, написать адаптивный запрос.

Например, вот так
    @Modifying
    @Query(value = "DELETE FROM Seller s WHERE s.externalId = :externalId")
    void deleteByExternalId(@Param("externalId") UUID externalId);

2023-03-07 15:56 UTC, DameerGamlet commented on seller-info-service/src/main/java/com/yandex/market/sellerinfoservice/service/impl/SellerServiceImpl.java
> +        Seller seller = getSellerByExternalId(sellerExternalId);
Это метод, как по мне, должен работать быстрее, чем метод, когда мы сначала ищет продавца по externalId с помощью метода getSellerByExternalId, а затем удаляем запись по его id с помощью метода deleteById.

Но если у кого-то есть в этом опыт и это не так, подскажите

2023-03-07 16:51 UTC, DameerGamlet approved these changes

2023-03-07 16:51 UTC, DameerGamlet commented on seller-info-service/src/test/java/com/yandex/market/sellerinfoservice/SellerInfoServiceApplicationTests.java
> +        mockMvc.perform(delete("/public/api/v1/sellers/" + SELLER_EXTERNAL_ID))
Может будем брать "/public/api/v1/sellers/" из переменной? Просто сейчас изменится версия и придётся менять все вхождения "/public/api/v1/sellers/" на "/public/api/v2/sellers/". Если забыть сделать - сломаются тесты

2023-03-07 16:51 UTC, DameerGamlet commented on seller-info-service/src/test/java/com/yandex/market/sellerinfoservice/SellerInfoServiceApplicationTests.java
> +        mockMvc.perform(delete("/public/api/v1/sellers/" + SELLER_EXTERNAL_ID))
в application-test.yml или как-то так есть этот путь (его мне кажется также можно внедрить в application-testcontainer, что ты делал)

2023-03-07 16:51 UTC, DameerGamlet commented on seller-info-service/src/test/java/com/yandex/market/sellerinfoservice/SellerInfoServiceApplicationTests.java
> +    @Sql("/db/insertTestSeller.sql")
SQL с параметром BEFORE подходит для всех этих целей. По мне так это более удобно, чем вещать на каждый метод выполнения запроса на добавление.

Посмотри как это реализовано в Классе-соседе SelelrControllerTest.

2023-03-07 16:51 UTC, DameerGamlet commented on seller-info-service/src/test/java/com/yandex/market/sellerinfoservice/SellerInfoServiceApplicationTests.java
> +    @Sql("/db/insertTestSeller.sql")
@Sql(scripts = {"classpath:db/insert_test_seller.sql"}, executionPhase = ExecutionPhase.BEFORE_TEST_METHOD)

2023-03-07 16:51 UTC, DameerGamlet commented on seller-info-service/src/test/java/com/yandex/market/sellerinfoservice/SellerInfoServiceApplicationTests.java
> +    @Sql("/db/insertTestSeller.sql")
Также принято называть скрипты с нижним подчёркиванием (a_b.sql) (либо дефиз (a-b.sql)). Например, insert_test_seller.sql

2023-03-08 09:52 UTC, eseoa requested changes

2023-03-08 09:52 UTC, eseoa commented on seller-info-service/src/main/java/com/yandex/market/sellerinfoservice/service/impl/SellerServiceImpl.java
> +        Seller seller = getSellerByExternalId(sellerExternalId);
`getSellerByExternalId `в методе сервиса должен возвращать `SellerResponseDto`, а там не содержится информация об  айдишнике пользователя. В 36 строчке помечено, что метод сделан чисто для теста. Вообще я зря его апрувнул изначально наверное. Поэтому как метод `getSellerByExternalId `будет доделан, твой метод перестанет работать. Можно сделать за два запроса к базе и за один, вот пример за два запроса:

`Seller seller = sellerRepository.getSellerByExternalId(sellerExternalId).orElseThrow(....);
  sellerRepository.delete....`

Чтобы сделать за одни запрос нужно идти в репозиторий и там создавать метод который возвращает тру если удалил пользователя и фолс если пользователь не найден. А потом в сервисе уже если пришло фолс из метода репозитория кидать эксепшн

2023-03-08 09:52 UTC, eseoa commented on seller-info-service/src/test/resources/application-testcontainers.yml
> +      url: /public/api/v1/sellers
```suggestion
      url: sellers
```
У нас есть пакет `com.yandex.market.util`
Где содержится `public/api/v1`
Поэтому лучше поменяй в этом пре `@RequestMapping`, чтобы потом это не делать

2023-03-08 09:55 UTC, seniorio-batonio commented on seller-info-service/src/main/java/com/yandex/market/sellerinfoservice/service/impl/SellerServiceImpl.java
> -    //На данный момент метод сделан чисто для теста, поэтому не Optional
Если есть что то для тестов - лучше делай для этого отдельный интерфейс. В данном случае в отдельный класс этот метод

2023-03-09 10:56 UTC, eseoa approved these changes

2023-03-09 14:45 UTC, NikPrg approved these changes

2023-03-09 14:45 UTC, NikPrg commented on seller-info-service/src/main/java/com/yandex/market/sellerinfoservice/controller/SellerController.java
> +        sellerService.deleteSeller(externalId);
подумай над названием, здесь нужно иметь четкое представление о методе и как он работает.

2023-03-09 14:53 UTC, NikPrg approved these changes

2023-03-09 14:54 UTC, NikPrg approved these changes

2023-03-09 14:56 UTC, merged