Getting seller by external Id
splendid-pdf/yandex-market pull request #92
Opened 2023-03-10 09:43 UTC by DameerGamlet

Страница:
![image](https://user-images.githubusercontent.com/74682814/224281981-a230d7d4-0124-4427-a391-dfed30726059.png)

2023-03-10 09:50 UTC, DameerGamlet commented
В модели отсуствует image для продавца, так что она не передаётся.

2023-03-10 21:27 UTC, eseoa requested changes

2023-03-10 21:27 UTC, eseoa commented on seller-info-service/src/main/java/com/yandex/market/sellerinfoservice/controller/SellerController.java
> +    public SellerResponseDto getSellerByExternalId(@PathVariable("sellerId") UUID sellerId) {
```suggestion
    public SellerResponseDto getSellerByExternalId(
        @Parameter(name = "externalId", description = "Индентификатор продавца"
        @PathVariable("sellerId")
        UUID sellerId
     ) {
```

2023-03-10 21:27 UTC, eseoa commented on seller-info-service/src/main/java/com/yandex/market/sellerinfoservice/controller/SellerController.java
> +    @Operation(operationId = "getProductByExternalId", summary = "Получение товара по externalId")
```suggestion
    @Operation(operationId = "getSellerByExternalId", summary = "Получение продавца по externalId")
```

2023-03-10 21:27 UTC, eseoa commented on seller-info-service/src/test/resources/application-test.yaml
>        url: /public/api/v1/sellers/
у нас есть commons `com.yandex.market.util.HttpUtils`

2023-03-11 11:24 UTC, AskarovFarkhad commented on seller-info-service/src/main/java/com/yandex/market/sellerinfoservice/controller/SellerController.java
>      @DeleteMapping("sellers/{externalId}")
Здесь в эндпоинте не sellerId должен быть по-хорошему? выше sellerId тут externalId

2023-03-11 11:24 UTC, AskarovFarkhad commented on seller-info-service/src/test/java/com/yandex/market/sellerinfoservice/SellerControllerTest.java
> +        UUID sellerId = UUID.fromString("37678201-f3c8-4d5c-a628-2344eef50c55");
Комментарии это не бест практик, название теста должно полностью оппределять что он из себя представляет, можно еще дописать что ожидается, например:
getSellerByExternalId_returnSellerResponseDtoAnd200IsOk()

2023-03-11 17:50 UTC, AskarovFarkhad approved these changes

2023-03-12 22:16 UTC, seniorio-batonio commented on seller-info-service/build.gradle
> +    id 'org.springframework.boot' version '3.0.2'
а чего версию понизил?

2023-03-12 22:18 UTC, seniorio-batonio approved these changes

2023-03-13 10:43 UTC, eseoa approved these changes

2023-03-13 10:44 UTC, merged